version: '3.3'
services:
  mongo:
    image: mongo
    restart: always
    # ports:
    #   - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

  golang:
    container_name: golang
    build:
      context: docker/golang
    restart: always
    volumes:
      - "./docker/data/golang:/go/:cached"
      - "./:/app:cached"
    ports:
      - 8080:8080
    links:
      - mongo
    depends_on:
      - mongo
